In [1]:
# Laboratorio2
# 22 de mayo
# Mauricio Medel De Jesús

In [2]:
import pandas as pd

In [5]:
# Conjunto de datos base para la generación del Big Data
datos = {
    "usuario": ["ana", "pepe", "luis", "rosita", "carolina", "paco"],
    "edad": [14, 22, 35, 40, 62, 70],
    "ciudad": ["cuitlahuac", "yanga", "atoyac", "paraje", "fortin", "cuichapa"],
    "compras_realizadas": [5, 10, 1, 2, 15, 3],
    "activo": [True, True, True, False, True, False],
    "fecha_registro": ["2026-01-10", "2026-05-21", "2026-02-10", "2026-03-11", "2026-04-10", "2026-05-01"]
}

In [8]:
#Creamos el dataframe
dfBigData = pd.DataFrame(datos)

In [11]:
dfBigData

    usuario  edad      ciudad  compras_realizadas  activo fecha_registro
0       ana    14  cuitlahuac                   5    True     2026-01-10
1      pepe    22       yanga                  10    True     2026-05-21
2      luis    35      atoyac                   1    True     2026-02-10
3    rosita    40      paraje                   2   False     2026-03-11
4  carolina    62      fortin                  15    True     2026-04-10
5      paco    70    cuichapa                   3   False     2026-05-01

In [17]:
#cantidada de registros 
cantidad = 1000000

In [18]:
import random

In [14]:
#crear el dataframe a 1000000 de registros

In [20]:
# Crear el dataFrame de 1000000 de registros
dfMillon = pd.DataFrame({
    "nombre": [random.choice(dfBigData["usuario"]) for _ in range(cantidad)],
    "edad": [random.randint(18, 80) for _ in range(cantidad)],
    "ciudad": [random.choice(dfBigData["ciudad"]) for _ in range(cantidad)],
    "compras_realizadas": [random.randint(1, 10) for _ in range(cantidad)],
    "activo": [random.choice(dfBigData["activo"]) for _ in range(cantidad)],
    "fecha_registro": [random.choice(dfBigData["fecha_registro"]) for _ in range(cantidad)]
})

In [21]:
dfBigData

    usuario  edad      ciudad  compras_realizadas  activo fecha_registro
0       ana    14  cuitlahuac                   5    True     2026-01-10
1      pepe    22       yanga                  10    True     2026-05-21
2      luis    35      atoyac                   1    True     2026-02-10
3    rosita    40      paraje                   2   False     2026-03-11
4  carolina    62      fortin                  15    True     2026-04-10
5      paco    70    cuichapa                   3   False     2026-05-01

In [22]:
dfMillon.shape

(1000000, 6)

In [23]:
dfMillon.dtypes

nombre                  str
edad                  int64
ciudad                  str
compras_realizadas    int64
activo                 bool
fecha_registro          str
dtype: object

In [24]:
dfMillon.memory_usage(deep = True)

Index                      132
nombre                61835060
edad                   8000000
ciudad                63835014
compras_realizadas     8000000
activo                 1000000
fecha_registro        67000000
dtype: int64

In [26]:
dfMillon.memory_usage(deep = True).sum()/1024**2

np.float64(199.95709037780762)